/**
 * Vite plugin that exposes any Greater Pipe manifests present in
 * `<repo>/data/pipes/*.manifest.json` to the Greater shell at build
 * time as the virtual module `virtual:greater-pipes`.
 *
 * The directory is gitignored. A clean public fork sees no manifests
 * and the virtual module exports an empty array — the shell then runs
 * in Generic mode and says so visibly. Production deployments mount
 * Pipes locally; the plugin picks them up on dev-server start (and
 * on filesystem changes via the watcher hook).
 *
 * Why a Vite plugin instead of a runtime fetch?
 *   1) keeps the proprietary manifests out of the public bundle (only
 *      the manifests actually present at build time get inlined);
 *   2) lets us validate them through @workspace/pipes' Zod parser
 *      and fail loudly at start-up if a manifest is malformed;
 *   3) avoids a runtime HTTP round-trip and CORS surface.
 */
import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { parsePipeManifest, type PipeManifest } from "@workspace/pipes";

const VIRTUAL_ID = "virtual:greater-pipes";
const RESOLVED_VIRTUAL_ID = "\0" + VIRTUAL_ID;

interface PipesLoaderOptions {
  /** Absolute path to the directory containing manifests. */
  pipesDir: string;
}

function loadManifests(pipesDir: string): {
  manifests: PipeManifest[];
  errors: string[];
} {
  if (!fs.existsSync(pipesDir)) return { manifests: [], errors: [] };
  const entries = fs
    .readdirSync(pipesDir)
    .filter((f) => f.endsWith(".manifest.json"));
  const manifests: PipeManifest[] = [];
  const errors: string[] = [];
  for (const file of entries) {
    const filePath = path.join(pipesDir, file);
    try {
      const raw = JSON.parse(fs.readFileSync(filePath, "utf-8"));
      manifests.push(parsePipeManifest(raw));
    } catch (err) {
      errors.push(
        `[greater-pipes] ${file}: ${(err as Error).message ?? String(err)}`,
      );
    }
  }
  return { manifests, errors };
}

export function pipesLoader(options: PipesLoaderOptions): Plugin {
  const { pipesDir } = options;
  let cache: { manifests: PipeManifest[]; errors: string[] } | null = null;

  function refresh() {
    cache = loadManifests(pipesDir);
    for (const e of cache.errors) {
      // Loud failure during dev — a bad manifest is almost always a
      // typo the author wants to see immediately.
      // eslint-disable-next-line no-console
      console.error(e);
    }
    if (cache.manifests.length > 0) {
      // eslint-disable-next-line no-console
      console.log(
        `[greater-pipes] loaded ${cache.manifests.length} pipe(s): ${cache.manifests
          .map((m) => `${m.pipe_id}@${m.version}`)
          .join(", ")}`,
      );
      // The runtime registry resolves at most one Pipe per persona via
      // PIPES.find(); flag collisions so the author knows that all but
      // the first manifest for a given persona will be ignored.
      const byPersona = new Map<string, string[]>();
      for (const m of cache.manifests) {
        const list = byPersona.get(m.persona) ?? [];
        list.push(m.pipe_id);
        byPersona.set(m.persona, list);
      }
      for (const [persona, ids] of byPersona) {
        if (ids.length > 1) {
          // eslint-disable-next-line no-console
          console.warn(
            `[greater-pipes] persona "${persona}" has ${ids.length} manifests (${ids.join(", ")}). The runtime will use "${ids[0]}" and ignore the rest.`,
          );
        }
      }
    }
  }

  return {
    name: "greater-pipes-loader",
    enforce: "pre",
    buildStart() {
      refresh();
    },
    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID;
      return null;
    },
    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;
      if (!cache) refresh();
      const manifests = cache?.manifests ?? [];
      // Inline the manifests as a const literal. Vite serves this as a
      // module; the runtime registry imports it.
      return [
        "// AUTO-GENERATED by greater-pipes-loader. Do not edit.",
        `export const PIPES = ${JSON.stringify(manifests, null, 2)};`,
      ].join("\n");
    },
    configureServer(server) {
      // Watch the pipes directory so a manifest add/remove triggers a
      // reload during dev. We can't use the standard watcher because
      // the directory is outside Vite's `root` (it lives at the repo
      // root); add it explicitly.
      if (fs.existsSync(pipesDir)) {
        server.watcher.add(pipesDir);
      }
      const onChange = (file: string) => {
        if (!file.startsWith(pipesDir)) return;
        if (!file.endsWith(".manifest.json")) return;
        refresh();
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
        if (mod) {
          server.moduleGraph.invalidateModule(mod);
          server.ws.send({ type: "full-reload" });
        }
      };
      server.watcher.on("add", onChange);
      server.watcher.on("change", onChange);
      server.watcher.on("unlink", onChange);
    },
  };
}
