kind = "web"
previewPath = "/"
title = "Greater"
version = "1.0.0"
id = "artifacts/greater"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 25794
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/greater run dev"

[services.env]
PORT = "25794"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/greater", "run", "build"]
publicDir = "artifacts/greater/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
